rootProject.name = "skillgain"

include(
    "app",
    "api",
    "bpmn",
    "config",
    "domain",
    "service",
    "ai",
    "repository",
    "migration",
    "exception",
    "security",
    "observability",
    "common"
)
include("api")
include("service")
include("ai")
include("bpmn")
include("domain")
include("repository")
include("migration")
include("config")
include("exception")
include("security")
include("observability")
include("common")
include("cache")