package net.skillgain.exception.domain.user

import net.skillgain.exception.domain.ErrorCode

enum class UserExceptionCode: ErrorCode {
    EMAIL_ALREADY_EXISTS,
    INVALID_USER_CREDENTIALS,
    USER_NOT_FOUND,
    ROLE_NOT_FOUND,
    PASSWORD_REQUIRED,
    ROLE_MODIFICATION_NOT_ALLOWED,
    INVALID_USER_ROLES,
    EMPTY_USER_ROLES,
    PASSWORD_CHANGE_REQUIRED,
    INVALID_INVITE_TOKEN,
    INVITE_TOKEN_EXPIRED,
    INVITE_TOKEN_ALREADY_USED,
    PASSWORD_MISMATCH,
    WEAK_PASSWORD,
    USER_DISABLED;
}